# Generated by Django 4.1.1 on 2022-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Enqueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('enquiry_date', models.DateTimeField()),
                ('solved_or_not', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('NOT SURE', 'NOT SURE')], max_length=100, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
                ('solution_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
