# Generated by Django 4.1.1 on 2022-10-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPSApp', '0002_db_enquiry_remove_db_enqueries_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_Enquiry',
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
