# Generated by Django 4.1.1 on 2022-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPSApp', '0003_delete_db_enquiry_db_enqueries_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_enqueries',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='db_enqueries',
            name='date',
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='enquiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='solution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='solution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='solved_or_not',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('NOT SURE', 'NOT SURE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='db_enqueries',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='db_enqueries',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
