# Generated by Django 4.1.1 on 2022-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPSApp', '0005_db_career_alter_db_enqueries_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_career',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
