# Generated by Django 4.1.1 on 2022-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPSApp', '0006_db_career_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('last_standerd_in_bps', models.CharField(choices=[('JR.KG', 'JR.KG'), ('1st Standerd', ''), ('2nd Standerd', ''), ('3rd Standerd', ''), ('4th Standerd', ''), ('5th Standerd', ''), ('6th Standerd', ''), ('7th Standerd', ''), ('8th Standerd', ''), ('9th Standerd', ''), ('10th Standerd', ''), ('11th Standerd', ''), ('12th Standerd', '')], max_length=100)),
                ('last_year_in_bps', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=100)),
                ('present_role', models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('OWNNER', 'OWNNER')], max_length=100)),
                ('company_or_bussiness_name', models.CharField(max_length=500)),
                ('sallary_or_turnover_LPA', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to='alumni_profile')),
                ('bussiness_photo', models.ImageField(upload_to='alumni_bussiness')),
            ],
        ),
    ]
