# Generated by Django 4.1.1 on 2022-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPSApp', '0007_db_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_alumni',
            name='bussiness_photo',
            field=models.ImageField(upload_to='alumni_application'),
        ),
        migrations.AlterField(
            model_name='db_alumni',
            name='profile_photo',
            field=models.ImageField(upload_to='alumni_application'),
        ),
    ]
